# Generated by Django 6.0 on 2025-12-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmember',
            name='last_read_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
